# Generated by Django 4.0.1 on 2022-05-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='payment_mode',
        ),
    ]
