# Generated by Django 4.0.1 on 2022-05-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_productorder_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='paid_status',
        ),
    ]
