# Generated by Django 4.0.1 on 2022-05-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_productorder_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='address',
            field=models.CharField(default='', max_length=260),
            preserve_default=False,
        ),
    ]
