# Generated by Django 4.0.1 on 2022-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_servicebooking_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='delivery_status',
        ),
    ]
