# Generated by Django 3.2.12 on 2022-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_productorder_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemen',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
        migrations.DeleteModel(
            name='ServiceMen',
        ),
    ]
