# Generated by Django 3.2.12 on 2022-06-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220604_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
    ]
