# Generated by Django 3.2.12 on 2022-06-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_product_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_name',
            new_name='vendor',
        ),
    ]
