# Generated by Django 3.2.12 on 2022-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_full_name_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='payment_id',
            field=models.CharField(default=1, max_length=36, verbose_name='Payment ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorder',
            name='provider_order_id',
            field=models.CharField(default=1, max_length=40, verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorder',
            name='signature_id',
            field=models.CharField(default=1, max_length=128, verbose_name='Signature ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorder',
            name='status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
