# Generated by Django 3.2.12 on 2022-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220610_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=10),
        ),
    ]
